-- XJTU PGC：回应系统 + 点赞同步校准
-- 直接复制到 Supabase SQL Editor 一次执行。
-- 不修改 public.notes 的字段或现有数据。

begin;

create table if not exists public.note_replies (
  id bigint generated by default as identity primary key,
  note_id bigint not null,
  content text not null check (char_length(trim(content)) between 1 and 180),
  nickname text not null default '热心西交er' check (char_length(trim(nickname)) between 1 and 30),
  created_at timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'note_replies_note_id_fkey'
      and conrelid = 'public.note_replies'::regclass
  ) then
    alter table public.note_replies
      add constraint note_replies_note_id_fkey
      foreign key (note_id) references public.notes(id) on delete cascade;
  end if;
end
$$;

create index if not exists note_replies_note_id_created_at_idx
  on public.note_replies (note_id, created_at asc);

alter table public.note_likes enable row level security;
alter table public.note_replies enable row level security;

revoke all on table public.note_likes from anon, authenticated;
grant select, insert on table public.note_likes to anon, authenticated;
revoke all on table public.note_replies from anon, authenticated;
grant select, insert on table public.note_replies to anon, authenticated;

do $$
declare
  likes_sequence text := pg_get_serial_sequence('public.note_likes', 'id');
  replies_sequence text := pg_get_serial_sequence('public.note_replies', 'id');
begin
  if likes_sequence is not null then
    execute format('grant usage, select on sequence %s to anon, authenticated', likes_sequence);
  end if;
  if replies_sequence is not null then
    execute format('grant usage, select on sequence %s to anon, authenticated', replies_sequence);
  end if;
end
$$;

drop policy if exists "note_likes_public_read" on public.note_likes;
drop policy if exists "note_likes_public_insert" on public.note_likes;
create policy "note_likes_public_read" on public.note_likes
  for select to anon, authenticated using (true);
create policy "note_likes_public_insert" on public.note_likes
  for insert to anon, authenticated with check (true);

drop policy if exists "note_replies_public_read" on public.note_replies;
drop policy if exists "note_replies_public_insert" on public.note_replies;
create policy "note_replies_public_read" on public.note_replies
  for select to anon, authenticated using (true);
create policy "note_replies_public_insert" on public.note_replies
  for insert to anon, authenticated with check (true);

-- 匿名访客没有 UPDATE/DELETE 权限和策略。

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'note_likes'
  ) then
    alter publication supabase_realtime add table public.note_likes;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'note_replies'
  ) then
    alter publication supabase_realtime add table public.note_replies;
  end if;
end
$$;

commit;

