-- XJTU PGC 秋招心愿情报墙：匿名点赞系统
-- 可直接复制到 Supabase SQL Editor 一次执行。
-- 本迁移只创建和配置 public.note_likes，不修改 public.notes。

begin;

-- 1. 创建点赞表。
-- note_id 类型应与当前 Supabase 默认 bigint notes.id 保持一致。
create table if not exists public.note_likes (
  id bigint generated by default as identity primary key,
  note_id bigint not null,
  created_at timestamptz not null default now()
);

-- 2. 添加外键；删除便利贴时自动删除对应点赞。
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'note_likes_note_id_fkey'
      and conrelid = 'public.note_likes'::regclass
  ) then
    alter table public.note_likes
      add constraint note_likes_note_id_fkey
      foreign key (note_id)
      references public.notes(id)
      on delete cascade;
  end if;
end
$$;

-- 3. 点赞数量查询索引。
create index if not exists note_likes_note_id_idx
  on public.note_likes (note_id);

create index if not exists note_likes_created_at_idx
  on public.note_likes (created_at desc);

-- 4. 启用 RLS。
alter table public.note_likes enable row level security;

-- 5. 重置 note_likes 的旧策略，避免多条 permissive policy 叠加。
do $$
declare
  policy_record record;
begin
  for policy_record in
    select policyname
    from pg_policies
    where schemaname = 'public'
      and tablename = 'note_likes'
  loop
    execute format(
      'drop policy if exists %I on public.note_likes',
      policy_record.policyname
    );
  end loop;
end
$$;

-- 6. 最小表级权限。
revoke all on table public.note_likes from anon, authenticated;
grant select, insert on table public.note_likes to anon, authenticated;

-- 兼容 identity/serial 及非默认序列名称。
do $$
declare
  likes_sequence text := pg_get_serial_sequence('public.note_likes', 'id');
begin
  if likes_sequence is not null then
    execute format(
      'grant usage, select on sequence %s to anon, authenticated',
      likes_sequence
    );
  end if;
end
$$;

-- 7. 所有访客都可以读取点赞记录，用于统计点赞数量。
create policy "note_likes_public_read"
on public.note_likes
for select
to anon, authenticated
using (true);

-- 8. 所有访客都可以给真实存在的便利贴点赞。
-- 外键保证 note_id 必须对应 public.notes 中的记录。
create policy "note_likes_public_insert"
on public.note_likes
for insert
to anon, authenticated
with check (true);

-- 不创建 UPDATE/DELETE 策略，匿名用户不能修改或删除点赞。

-- 9. 加入 Supabase Realtime，使其他设备实时收到点赞变化。
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'note_likes'
  ) then
    alter publication supabase_realtime add table public.note_likes;
  end if;
end
$$;

commit;

-- 无需触发器：
-- 1. created_at 使用数据库默认值 now()；
-- 2. 删除便利贴时由外键 on delete cascade 清理点赞；
-- 3. 点赞数量由前端关联查询 note_likes(count) 并通过 Realtime 更新。

